services:
  # Backend Service
  - type: web
    name: kindplate-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: kindplate-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://kindplate-frontend.onrender.com
    healthCheckPath: /health

  # Frontend Service  
  - type: web
    name: kindplate-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_BACKEND_BASE_URL
        value: https://kindplate-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Database
  - type: pserv
    name: kindplate-db
    plan: free
    databaseName: kindplate
    user: kindplate_user
